intervals:
  graphs: 1.0
  processes: 2.0
  temperature: 5.0
  network: 1.0
colors:
  cpu_graph: green
  gpu_graph: red
  memory_graph: blue
  disk_read: blue
  disk_write: red
  network_download: green
  network_upload: orange
  temperature: orange
  warning: yellow
  error: red
display:
  graph_history: 60
  process_count: 10
  partition_count: 3
  interface_count: 3
  show_gpu: true
  show_temperature: true
  compact_mode: false
alerts:
  cpu_temp_warning: 70
  cpu_temp_critical: 85
  gpu_temp_warning: 75
  gpu_temp_critical: 90
  enable_notifications: true
default_tab: system
theme: dark
log_level: INFO
